<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/wallet.proto

namespace Grpc\Wallet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>wallet.GenerateWalletResponse</code>
 */
class GenerateWalletResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string public_address = 1;</code>
     */
    protected $public_address = '';
    /**
     * Generated from protobuf field <code>string private_key = 2;</code>
     */
    protected $private_key = '';
    /**
     * Generated from protobuf field <code>string network = 3;</code>
     */
    protected $network = '';
    /**
     * Generated from protobuf field <code>string mnemonic = 4;</code>
     */
    protected $mnemonic = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $public_address
     *     @type string $private_key
     *     @type string $network
     *     @type string $mnemonic
     * }
     */
    public function __construct($data = NULL) {
        \Grpc\GPBMetadata\Wallet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string public_address = 1;</code>
     * @return string
     */
    public function getPublicAddress()
    {
        return $this->public_address;
    }

    /**
     * Generated from protobuf field <code>string public_address = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPublicAddress($var)
    {
        GPBUtil::checkString($var, True);
        $this->public_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string private_key = 2;</code>
     * @return string
     */
    public function getPrivateKey()
    {
        return $this->private_key;
    }

    /**
     * Generated from protobuf field <code>string private_key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPrivateKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->private_key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string network = 3;</code>
     * @return string
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * Generated from protobuf field <code>string network = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setNetwork($var)
    {
        GPBUtil::checkString($var, True);
        $this->network = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string mnemonic = 4;</code>
     * @return string
     */
    public function getMnemonic()
    {
        return $this->mnemonic;
    }

    /**
     * Generated from protobuf field <code>string mnemonic = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMnemonic($var)
    {
        GPBUtil::checkString($var, True);
        $this->mnemonic = $var;

        return $this;
    }

}

