<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: protos/wallet.proto

namespace Grpc\Wallet;

use Spiral\RoadRunner\GRPC;

interface WalletServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "wallet.WalletService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param GenerateWalletRequest $in
    * @return GenerateWalletResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function GenerateWallet(GRPC\ContextInterface $ctx, GenerateWalletRequest $in): GenerateWalletResponse;
}
